//
//  AllPosibilities.swift
//  Nukon
//
//  Created by Kaichi Momose on 2017/11/21.
//  Copyright © 2017 Kaichi Momose. All rights reserved.
//

import Foundation

struct Posibilities {
    let sound: String
    let posibilitiesList: [[String]]
}

struct AllPosibilities {
    let allPosibilitiesList = [Posibilities(sound: "vowel",
                                            posibilitiesList: [["あ", "あー", "ああ"],
                                                               ["い", "いー", "いい", "1", "飯", "いーいー"],
                                                               ["う", "うー", "うう", "雨雨","雨", "うん", "生生"],
                                                               ["え", "えー", "笑", "へ", "Ai"],
                                                               ["お", "おー", "を", "おお"],
                                                               [" "]]),
                               Posibilities(sound: "K",
                                            posibilitiesList: [["家", "か", "Cars"],
                                                               ["き", "キー"],
                                                               ["9", "く", "空空"],
                                                               ["けー", "け", "けーけー", "Kate", "家家", "兄兄"],
                                                               ["こ", "子", "神神"],
                                                               [" "]]),
                               Posibilities(sound: "S",
                                            posibilitiesList: [["Sara", "左", "さ", "さぁ", "3", "左左"],
                                                               ["7", "シー","私", "しーしー", "氏", "し"],
                                                               ["す", "数", "すー"],
                                                               ["せ", "西", "生", "瀬", "聖"],
                                                               ["うそ", "そう", "そ", "奏", "そっ", "ソ"],
                                                               [" "]]),
                               Posibilities(sound: "T",
                                            posibilitiesList: [["た", "太", "たー"],
                                                               ["千", "遅", "ち", "ちー", "ちい", "乳乳"],
                                                               ["通", "つ", "ツ"],
                                                               ["Perez", "て", "TV", "笑", "."],
                                                               ["と", "頭"],
                                                               [" "]]),
                               Posibilities(sound: "N",
                                            posibilitiesList: [["な", "なぁ", "名", "なな"],
                                                               ["2", "に"],
                                                               ["2", "ぬー", "ぬぬ", "ぬーぬー"],
                                                               ["ね", "ねー", "ねぇねぇ"],
                                                               ["の", "のー", "ノー"],
                                                               ["ん", "うん", "んん"]]),
                               Posibilities(sound: "H",
                                            posibilitiesList: [["は", "はは", "はぁ", "波", "母", "はい", "はあ"],
                                                               ["ひ", "ひー", "日", "火"],
                                                               ["父", "布", "風", "付", "歩", "ふ"],
                                                               ["へ", "辺", "へい", "Hey", "へー"],
                                                               ["歩", "ほ", "法"],
                                                               [" "]]),
                               Posibilities(sound: "M",
                                            posibilitiesList: [["Marle", "間", "今", "まぁ", "まま", "馬", "ま", "磨"],
                                                               ["実", "ミー", "み", "御"],
                                                               ["M", "6", "ムー", "む"],
                                                               ["女", "め", "目", "明"],
                                                               ["も", "もう"],
                                                               [" "]]),
                               Posibilities(sound: "Y",
                                            posibilitiesList: [["や", "いや", "8", "やー"],
                                                               ["　"],
                                                               ["ユウ","油", "結", "(有)", "祐", "ユ", "湯"],
                                                               ["　"],
                                                               ["Yo", "夜", "よ", "4"],
                                                               [" "]]),
                               Posibilities(sound: "R",
                                            posibilitiesList: [["Lact", "ら", "ラ", "らー"],
                                                               ["り", "Willie", "リー", "リ", "りー", "りーりー"],
                                                               ["流", "る", "ルー"],
                                                               ["0", "れ", "上", "レ"],
                                                               ["Rola", "ろう", "ろ"],
                                                               [" "]]),
                               Posibilities(sound: "W",
                                            posibilitiesList: [["わ", "わー", "わーわー", "話", "=", "わわ", "わわわ"],
                                                               ["　"],
                                                               ["　"],
                                                               ["　"],
                                                               ["Wow", "お"],
                                                               [" "]])]

    let allVoicedPosibilitiesList = [Posibilities(sound: "G",
                                            posibilitiesList: [["が", "雅", "我"],
                                                               ["ぎ", "着", "技", "ギー", "偽", "戯"],
                                                               ["ぐ","Goo", "グ", "グー"],
                                                               ["げ", "夏", "下", "ゲー", "家", "Jeff", "げー"],
                                                               ["ご", "5", "後"],
                                                               [" "]]),
                                   Posibilities(sound: "Z",
                                                posibilitiesList: [["ザ", "ざ", "いざ", "うざっ"],
                                                                   ["じ", "次", "時", "字", "ジー"],
                                                                   ["ず","づ", "頭","豆"],
                                                                   ["ぜ", "ゼ"],
                                                                   ["ぞ", "蔵", "ぞう", "ぞー"],
                                                                   [" "]]),
                                   Posibilities(sound: "D",
                                                posibilitiesList: [["だ"],
                                                                   ["ぢ", "次", "時", "字", "ジー"],
                                                                   ["頭","豆"],
                                                                   ["で"],
                                                                   ["ど", "渡", "度", "土", "ド", "怒", "どう"],
                                                                   [" "]]),
                                   Posibilities(sound: "B",
                                                posibilitiesList: [["ば", "場", "バー", "馬場", "婆"],
                                                                   ["び", "びー", "ビー"],
                                                                   ["ぶ","分", "ぶー", "武"],
                                                                   ["べ", "米", "べー", "べーべー"],
                                                                   ["ぼ", "母", "|"],
                                                                   [" "]]),
                                   Posibilities(sound: "P",
                                                posibilitiesList: [["ぱ", "波", "パ", "ぱー", "Pablo"],
                                                                   ["ぴ", "ピー", "日", "ぴー", "ぴーぴー"],
                                                                   ["ぷ", "風", "プ"],
                                                                   ["ぺ", "Perez"],
                                                                   ["ぽ", "歩", "泡"],
                                                                   ["　"]])]
    
    let allYVowelPosibilitiesList = [Posibilities(sound: "Ky",
                                            posibilitiesList: [["Cash", "きゃ", "きゃー"],
                                                               ["　"],
                                                               ["9","きゅ", "99"],
                                                               ["　"],
                                                               ["今日", "きょ"],
                                                               [" "]]),
                               Posibilities(sound: "Sy",
                                            posibilitiesList: [["車", "しゃ", "車車"],
                                                               ["　"],
                                                               ["しゅ","酒", "手", "秋"],
                                                               ["　"],
                                                               ["しょ", "初", "笑"],
                                                               [" "]]),
                               Posibilities(sound: "Cy",
                                            posibilitiesList: [["ちゃ", "チャ", "チャチャ", "ちゃー"],
                                                               ["　"],
                                                               ["ちゅ", "中", "10"],
                                                               ["　"],
                                                               ["朝", "Joey", "John", "ちょ"],
                                                               [" "]]),
                               Posibilities(sound: "Ny",
                                            posibilitiesList: [["いや", "にゃ", "にゃー"],
                                                               ["　"],
                                                               ["2","ニュー", "にゅ", "Nu", "入", "乳", "乳乳"],
                                                               ["　"],
                                                               ["女", "4", "にょ", "尿"],
                                                               ["　"]]),
                               Posibilities(sound: "Hy",
                                            posibilitiesList: [["100", "ひゃ"],
                                                               ["　"],
                                                               ["ひゅ", "ヒュー", "ヒューヒュー"],
                                                               ["　"],
                                                               ["氷", "ひょ"],
                                                               [" "]]),
                               Posibilities(sound: "My",
                                            posibilitiesList: [["宮", "みゃ", "今"],
                                                               ["　"],
                                                               ["自由","みゅ", "みゅー", "みゅーみゅー"],
                                                               ["　"],
                                                               ["明", "みょ"],
                                                               [" "]]),
                               Posibilities(sound: "Ry",
                                            posibilitiesList: [["りゃ", "裏", "いや"],
                                                               ["　"],
                                                               ["流","涙", "りゅ"],
                                                               ["　"],
                                                               ["りょう", "りょ"],
                                                               [" "]])]

}
