//
//  AllPosibilities.swift
//  Nukon
//
//  Created by Kaichi Momose on 2017/11/21.
//  Copyright © 2017 Kaichi Momose. All rights reserved.
//

import Foundation

struct Posibilities {
    let sound: String
    let posibilitiesList: [[String]]
}

struct AllPosibilities {
    let allPosibilitiesList = [Posibilities(sound: "vowel",
                                            posibilitiesList: [["あ", "あー", "ああ"],
                                                               ["1", "い", "いー", "飯", "いい"],
                                                               ["Phi","雨", "うー", "う", "うん"],
                                                               ["笑", "へ", "Ai"],
                                                               ["お", "を", "おお", "おー"],
                                                               [" "]]),
                               Posibilities(sound: "K",
                                            posibilitiesList: [["家", "か"],
                                                               ["き", "生", "日"],
                                                               ["9", "く", "歩"],
                                                               ["けー", "Kate", "け"],
                                                               ["こ", "子"],
                                                               [" "]]),
                               Posibilities(sound: "S",
                                            posibilitiesList: [["Sara", "左", "さ", "さぁ", "3"],
                                                               ["4", "7", "私", "次", "子", "氏", "し"],
                                                               ["す","数", "雛", "すー", "生", "歩"],
                                                               ["西", "青", "せ", "生", "瀬", "聖"],
                                                               ["うそ", "そう", "そ", "奏", "そっ", "ソ"],
                                                               [" "]]),
                               Posibilities(sound: "T",
                                            posibilitiesList: [["た", "波", "太"],
                                                               ["千", "4", "遅", "1","ち", "ちー"],
                                                               ["頭","通", "つ", "ツ"],
                                                               ["Perez", "て", "TV", "笑", "."],
                                                               ["と", "頭", "渡"],
                                                               [" "]]),
                               Posibilities(sound: "N",
                                            posibilitiesList: [["な", "なぁ", "名"],
                                                               ["2", "に", "仁", "飯", "位", "いい"],
                                                               ["2","ニュー", "6", "犬", "エヌ", "歩", "乳", "Nu", "入", "ぬー", "Phi", "流"],
                                                               ["ね", "音", "子", "寝", "値"],
                                                               ["の", "を", "男", "生", "小", "おお", "おー", "のー", "ノー"],
                                                               ["ん", "うん", "んん"]]),
                               Posibilities(sound: "H",
                                            posibilitiesList: [["は", "はは", "はぁ", "波", "母", "はい", "はあ"],
                                                               ["ひ", "日", "氷", "匹", "火", "灯"],
                                                               ["Phi", "父", "布", "風", "付", "歩", "ふ"],
                                                               ["Phi", "へ", "辺", "経", "回", "へ", "Ai"],
                                                               ["歩", "保", "ほ"],
                                                               [" "]]),
                               Posibilities(sound: "M",
                                            posibilitiesList: [["Marle", "間", "今", "まぁ", "まま", "馬", "ま", "磨"],
                                                               ["実", "笑", "ミー", "味", "未","海" ,"明", "み", "御"],
                                                               ["Phi","M", "6", "風", "夢", "犬", "向", "武", "ムー", "む"],
                                                               ["女", "め", "目", "明"],
                                                               ["の", "も", "母", "もう"],
                                                               [" "]]),
                               Posibilities(sound: "Y",
                                            posibilitiesList: [["や", "いや", "8", "家", "熊野", "夜", "谷", "屋", "爺"],
                                                               ["　"],
                                                               ["ユウ","油", "行", "結", "(有)", "祐", "ユ", "湯", "うん"],
                                                               ["　"],
                                                               ["4", "Yo", "夜", "よ", "好"],
                                                               [" "]]),
                               Posibilities(sound: "R",
                                            posibilitiesList: [["Lact", "ら", "ラ", "らー", "裏"],
                                                               ["り", "裏", "理", "びー", "日", "ディー", "リー", "リ"],
                                                               ["流","涙", "る", "ルー", "生"],
                                                               ["0", "れ", "で", "俺", "上", "ね", "例", "手", "出", "レ"],
                                                               ["Rola", "6", "ろう", "ろ", "狼", "籠"],
                                                               [" "]]),
                               Posibilities(sound: "W",
                                            posibilitiesList: [["は", "わ", "=", "話", "波", "和", "端", "我"],
                                                               ["　"],
                                                               ["　"],
                                                               ["　"],
                                                               ["お", "を", "男", "生", "小", "おお", "おー", "Wow"],
                                                               [" "]])]

    let allVoicedPosibilitiesList = [Posibilities(sound: "G",
                                            posibilitiesList: [["が", "雅", "我"],
                                                               ["ぎ", "着", "技", "ギー", "偽", "戯"],
                                                               ["ぐ","Goo", "グ", "グー", "9"],
                                                               ["げ", "夏", "下", "ゲー", "家", "Jeff", "で"],
                                                               ["ご", "5", "後"],
                                                               [" "]]),
                                   Posibilities(sound: "Z",
                                                posibilitiesList: [["ザ", "ざ", "いざ", "うざっ"],
                                                                   ["じ", "次", "時", "字"],
                                                                   ["ず","づ", "頭","豆"],
                                                                   ["ぜ", "ゼ"],
                                                                   ["ぞ", "蔵", "ぞう", "ぞー"],
                                                                   [" "]]),
                                   Posibilities(sound: "D",
                                                posibilitiesList: [["だ"],
                                                                   ["ぢ", "次", "時", "字"],
                                                                   ["頭","豆"],
                                                                   ["で"],
                                                                   ["ど", "渡", "度", "土", "ド", "怒", "どう"],
                                                                   [" "]]),
                                   Posibilities(sound: "B",
                                                posibilitiesList: [["ば", "場", "バー", "馬場", "婆", "腹", "Marle"],
                                                                   ["び", "びー", "ビー", "日"],
                                                                   ["ぶ","分", "ぶー", "武", "Phi"],
                                                                   ["べ", "米", "辺", "Perez"],
                                                                   ["ぼ", "母", "|", "と"],
                                                                   [" "]]),
                                   Posibilities(sound: "P",
                                                posibilitiesList: [["ぱ", "波", "パ"],
                                                                   ["ぴ", "ピー", "日"],
                                                                   ["Phi", "ぷ", "風", "プ", "9"],
                                                                   ["ぺ", "Perez", "辺"],
                                                                   ["ぽ", "歩"],
                                                                   ["　"]])]
    
    let allYVowelPosibilitiesList = [Posibilities(sound: "Ky",
                                            posibilitiesList: [["Cash", "きゃ", "きゃー"],
                                                               ["　"],
                                                               ["9","きゅ"],
                                                               ["　"],
                                                               ["今日", "きょ"],
                                                               [" "]]),
                               Posibilities(sound: "Sy",
                                            posibilitiesList: [["車", "しゃ"],
                                                               ["　"],
                                                               ["しゅ","酒", "手"],
                                                               ["　"],
                                                               ["しょ", "初", "笑"],
                                                               [" "]]),
                               Posibilities(sound: "Cy",
                                            posibilitiesList: [["ちゃ", "じゃー", "Jack"],
                                                               ["　"],
                                                               ["10", "ちゅ"],
                                                               ["　"],
                                                               ["朝", "Joey", "John", "ちょ"],
                                                               [" "]]),
                               Posibilities(sound: "Ny",
                                            posibilitiesList: [["いや", "にゃ", "宮"],
                                                               ["　"],
                                                               ["2","ニュー", "にゅ", "Nu", "入"],
                                                               ["　"],
                                                               ["女", "4", "にょ"],
                                                               ["　"]]),
                               Posibilities(sound: "Hy",
                                            posibilitiesList: [["100", "ひゃ"],
                                                               ["　"],
                                                               ["9", "日", "ひゅ", "酒"],
                                                               ["　"],
                                                               ["氷", "ひょ"],
                                                               [" "]]),
                               Posibilities(sound: "My",
                                            posibilitiesList: [["宮", "みゃ", "今"],
                                                               ["　"],
                                                               ["自由","みょ"],
                                                               ["　"],
                                                               ["明", "みょ"],
                                                               [" "]]),
                               Posibilities(sound: "Ry",
                                            posibilitiesList: [["いや", "りゃ", "裏"],
                                                               ["　"],
                                                               ["流","涙", "りゅ", "ルー", "生"],
                                                               ["　"],
                                                               ["Yo", "りょう", "りょ"],
                                                               [" "]])]

}
